#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MP_Chess.Resource", IsApplication=true)]

namespace MP_Chess
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int green = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int grey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int sample_0 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sample_1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sample_2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sample_3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sample_4 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sample_5 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sample_6 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sample_7 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int white = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int ChessSquare00 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int ChessSquare01 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int ChessSquare02 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int ChessSquare03 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int ChessSquare04 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int ChessSquare05 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int ChessSquare06 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int ChessSquare07 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int ChessSquare10 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int ChessSquare11 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int ChessSquare12 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int ChessSquare13 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int ChessSquare14 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int ChessSquare15 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int ChessSquare16 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int ChessSquare17 = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int ChessSquare20 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int ChessSquare21 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int ChessSquare22 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int ChessSquare23 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int ChessSquare24 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int ChessSquare25 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int ChessSquare26 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int ChessSquare27 = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int ChessSquare30 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int ChessSquare31 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int ChessSquare32 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int ChessSquare33 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int ChessSquare34 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int ChessSquare35 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int ChessSquare36 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int ChessSquare37 = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int ChessSquare40 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int ChessSquare41 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int ChessSquare42 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int ChessSquare43 = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int ChessSquare44 = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int ChessSquare45 = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int ChessSquare46 = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int ChessSquare47 = 2131099694;
			
			// aapt resource value: 0x7f060030
			public const int ChessSquare50 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int ChessSquare51 = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int ChessSquare52 = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int ChessSquare53 = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int ChessSquare54 = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int ChessSquare55 = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int ChessSquare56 = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int ChessSquare57 = 2131099703;
			
			// aapt resource value: 0x7f060039
			public const int ChessSquare60 = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int ChessSquare61 = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int ChessSquare62 = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int ChessSquare63 = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int ChessSquare64 = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int ChessSquare65 = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int ChessSquare66 = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int ChessSquare67 = 2131099712;
			
			// aapt resource value: 0x7f060042
			public const int ChessSquare70 = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int ChessSquare71 = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int ChessSquare72 = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int ChessSquare73 = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int ChessSquare74 = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int ChessSquare75 = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int ChessSquare76 = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int ChessSquare77 = 2131099721;
			
			// aapt resource value: 0x7f060053
			public const int ConnectButton = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int ErrorText = 2131099732;
			
			// aapt resource value: 0x7f06004a
			public const int ExitButton = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int GridButton = 2131099723;
			
			// aapt resource value: 0x7f060000
			public const int HeadText = 2131099648;
			
			// aapt resource value: 0x7f060050
			public const int ServerText = 2131099728;
			
			// aapt resource value: 0x7f060052
			public const int UserText = 2131099730;
			
			// aapt resource value: 0x7f06004d
			public const int chessboard = 2131099725;
			
			// aapt resource value: 0x7f06004c
			public const int gridLayout1 = 2131099724;
			
			// aapt resource value: 0x7f060057
			public const int piece = 2131099735;
			
			// aapt resource value: 0x7f060055
			public const int square = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int square_background = 2131099734;
			
			// aapt resource value: 0x7f060001
			public const int tableLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int tableRow1 = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int tableRow2 = 2131099659;
			
			// aapt resource value: 0x7f060014
			public const int tableRow3 = 2131099668;
			
			// aapt resource value: 0x7f06001d
			public const int tableRow4 = 2131099677;
			
			// aapt resource value: 0x7f060026
			public const int tableRow5 = 2131099686;
			
			// aapt resource value: 0x7f06002f
			public const int tableRow6 = 2131099695;
			
			// aapt resource value: 0x7f060038
			public const int tableRow7 = 2131099704;
			
			// aapt resource value: 0x7f060041
			public const int tableRow8 = 2131099713;
			
			// aapt resource value: 0x7f06004f
			public const int textView1 = 2131099727;
			
			// aapt resource value: 0x7f06004e
			public const int textView2 = 2131099726;
			
			// aapt resource value: 0x7f060051
			public const int textView3 = 2131099729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Chess = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Chessboard = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int square = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int callHistory = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
