#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MP_Chess.Resource", IsApplication=true)]

namespace MP_Chess
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BlackBishop = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BlackKing = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BlackKnight = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BlackPawn = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BlackQueen = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int BlackRook = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int blank = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int green = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int grey = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sample_0 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int sample_1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sample_2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sample_3 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int sample_4 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int sample_5 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int sample_6 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int sample_7 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int white = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int WhiteBishop = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int WhiteKing = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int WhiteKnight = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int WhitePawn = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int WhiteQueen = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int WhiteRook = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int A0 = 2131099663;
			
			// aapt resource value: 0x7f060019
			public const int A1 = 2131099673;
			
			// aapt resource value: 0x7f060023
			public const int A2 = 2131099683;
			
			// aapt resource value: 0x7f06002d
			public const int A3 = 2131099693;
			
			// aapt resource value: 0x7f060037
			public const int A4 = 2131099703;
			
			// aapt resource value: 0x7f060041
			public const int A5 = 2131099713;
			
			// aapt resource value: 0x7f06004b
			public const int A6 = 2131099723;
			
			// aapt resource value: 0x7f060055
			public const int A7 = 2131099733;
			
			// aapt resource value: 0x7f060010
			public const int B0 = 2131099664;
			
			// aapt resource value: 0x7f06001a
			public const int B1 = 2131099674;
			
			// aapt resource value: 0x7f060024
			public const int B2 = 2131099684;
			
			// aapt resource value: 0x7f06002e
			public const int B3 = 2131099694;
			
			// aapt resource value: 0x7f060038
			public const int B4 = 2131099704;
			
			// aapt resource value: 0x7f060042
			public const int B5 = 2131099714;
			
			// aapt resource value: 0x7f06004c
			public const int B6 = 2131099724;
			
			// aapt resource value: 0x7f060056
			public const int B7 = 2131099734;
			
			// aapt resource value: 0x7f060004
			public const int Blank0 = 2131099652;
			
			// aapt resource value: 0x7f060011
			public const int C0 = 2131099665;
			
			// aapt resource value: 0x7f06001b
			public const int C1 = 2131099675;
			
			// aapt resource value: 0x7f060025
			public const int C2 = 2131099685;
			
			// aapt resource value: 0x7f06002f
			public const int C3 = 2131099695;
			
			// aapt resource value: 0x7f060039
			public const int C4 = 2131099705;
			
			// aapt resource value: 0x7f060043
			public const int C5 = 2131099715;
			
			// aapt resource value: 0x7f06004d
			public const int C6 = 2131099725;
			
			// aapt resource value: 0x7f060057
			public const int C7 = 2131099735;
			
			// aapt resource value: 0x7f060066
			public const int ChatDisplay = 2131099750;
			
			// aapt resource value: 0x7f06006f
			public const int ConnectButton = 2131099759;
			
			// aapt resource value: 0x7f060012
			public const int D0 = 2131099666;
			
			// aapt resource value: 0x7f06001c
			public const int D1 = 2131099676;
			
			// aapt resource value: 0x7f060026
			public const int D2 = 2131099686;
			
			// aapt resource value: 0x7f060030
			public const int D3 = 2131099696;
			
			// aapt resource value: 0x7f06003a
			public const int D4 = 2131099706;
			
			// aapt resource value: 0x7f060044
			public const int D5 = 2131099716;
			
			// aapt resource value: 0x7f06004e
			public const int D6 = 2131099726;
			
			// aapt resource value: 0x7f060058
			public const int D7 = 2131099736;
			
			// aapt resource value: 0x7f060013
			public const int E0 = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int E1 = 2131099677;
			
			// aapt resource value: 0x7f060027
			public const int E2 = 2131099687;
			
			// aapt resource value: 0x7f060031
			public const int E3 = 2131099697;
			
			// aapt resource value: 0x7f06003b
			public const int E4 = 2131099707;
			
			// aapt resource value: 0x7f060045
			public const int E5 = 2131099717;
			
			// aapt resource value: 0x7f06004f
			public const int E6 = 2131099727;
			
			// aapt resource value: 0x7f060059
			public const int E7 = 2131099737;
			
			// aapt resource value: 0x7f060070
			public const int ErrorText = 2131099760;
			
			// aapt resource value: 0x7f060067
			public const int ExitButton = 2131099751;
			
			// aapt resource value: 0x7f060014
			public const int F0 = 2131099668;
			
			// aapt resource value: 0x7f06001e
			public const int F1 = 2131099678;
			
			// aapt resource value: 0x7f060028
			public const int F2 = 2131099688;
			
			// aapt resource value: 0x7f060032
			public const int F3 = 2131099698;
			
			// aapt resource value: 0x7f06003c
			public const int F4 = 2131099708;
			
			// aapt resource value: 0x7f060046
			public const int F5 = 2131099718;
			
			// aapt resource value: 0x7f060050
			public const int F6 = 2131099728;
			
			// aapt resource value: 0x7f06005a
			public const int F7 = 2131099738;
			
			// aapt resource value: 0x7f060015
			public const int G0 = 2131099669;
			
			// aapt resource value: 0x7f06001f
			public const int G1 = 2131099679;
			
			// aapt resource value: 0x7f060029
			public const int G2 = 2131099689;
			
			// aapt resource value: 0x7f060033
			public const int G3 = 2131099699;
			
			// aapt resource value: 0x7f06003d
			public const int G4 = 2131099709;
			
			// aapt resource value: 0x7f060047
			public const int G5 = 2131099719;
			
			// aapt resource value: 0x7f060051
			public const int G6 = 2131099729;
			
			// aapt resource value: 0x7f06005b
			public const int G7 = 2131099739;
			
			// aapt resource value: 0x7f060016
			public const int H0 = 2131099670;
			
			// aapt resource value: 0x7f060020
			public const int H1 = 2131099680;
			
			// aapt resource value: 0x7f06002a
			public const int H2 = 2131099690;
			
			// aapt resource value: 0x7f060034
			public const int H3 = 2131099700;
			
			// aapt resource value: 0x7f06003e
			public const int H4 = 2131099710;
			
			// aapt resource value: 0x7f060048
			public const int H5 = 2131099720;
			
			// aapt resource value: 0x7f060052
			public const int H6 = 2131099730;
			
			// aapt resource value: 0x7f06005c
			public const int H7 = 2131099740;
			
			// aapt resource value: 0x7f060000
			public const int HeadText = 2131099648;
			
			// aapt resource value: 0x7f060071
			public const int JoinGame = 2131099761;
			
			// aapt resource value: 0x7f06005d
			public const int MoveBlock = 2131099741;
			
			// aapt resource value: 0x7f060061
			public const int MoveButton = 2131099745;
			
			// aapt resource value: 0x7f06005e
			public const int MoveFrom = 2131099742;
			
			// aapt resource value: 0x7f060060
			public const int MoveTo = 2131099744;
			
			// aapt resource value: 0x7f060064
			public const int MsgText = 2131099748;
			
			// aapt resource value: 0x7f060005
			public const int NumberAcross0 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int NumberAcross1 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int NumberAcross2 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int NumberAcross3 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int NumberAcross4 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int NumberAcross5 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int NumberAcross6 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int NumberAcross7 = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int NumberDown0 = 2131099662;
			
			// aapt resource value: 0x7f060018
			public const int NumberDown1 = 2131099672;
			
			// aapt resource value: 0x7f060022
			public const int NumberDown2 = 2131099682;
			
			// aapt resource value: 0x7f06002c
			public const int NumberDown3 = 2131099692;
			
			// aapt resource value: 0x7f060036
			public const int NumberDown4 = 2131099702;
			
			// aapt resource value: 0x7f060040
			public const int NumberDown5 = 2131099712;
			
			// aapt resource value: 0x7f06004a
			public const int NumberDown6 = 2131099722;
			
			// aapt resource value: 0x7f060054
			public const int NumberDown7 = 2131099732;
			
			// aapt resource value: 0x7f06006e
			public const int OpponentText = 2131099758;
			
			// aapt resource value: 0x7f060063
			public const int SendBlock = 2131099747;
			
			// aapt resource value: 0x7f060065
			public const int SendButton = 2131099749;
			
			// aapt resource value: 0x7f06006a
			public const int ServerText = 2131099754;
			
			// aapt resource value: 0x7f06006c
			public const int UserText = 2131099756;
			
			// aapt resource value: 0x7f060068
			public const int chessboard = 2131099752;
			
			// aapt resource value: 0x7f060062
			public const int gridLayout1 = 2131099746;
			
			// aapt resource value: 0x7f060074
			public const int piece = 2131099764;
			
			// aapt resource value: 0x7f060072
			public const int square = 2131099762;
			
			// aapt resource value: 0x7f060073
			public const int square_background = 2131099763;
			
			// aapt resource value: 0x7f060002
			public const int tableLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int tableRow0 = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int tableRow1 = 2131099661;
			
			// aapt resource value: 0x7f060017
			public const int tableRow2 = 2131099671;
			
			// aapt resource value: 0x7f060021
			public const int tableRow3 = 2131099681;
			
			// aapt resource value: 0x7f06002b
			public const int tableRow4 = 2131099691;
			
			// aapt resource value: 0x7f060035
			public const int tableRow5 = 2131099701;
			
			// aapt resource value: 0x7f06003f
			public const int tableRow6 = 2131099711;
			
			// aapt resource value: 0x7f060049
			public const int tableRow7 = 2131099721;
			
			// aapt resource value: 0x7f060053
			public const int tableRow8 = 2131099731;
			
			// aapt resource value: 0x7f06005f
			public const int textView1 = 2131099743;
			
			// aapt resource value: 0x7f060069
			public const int textView2 = 2131099753;
			
			// aapt resource value: 0x7f06006b
			public const int textView3 = 2131099755;
			
			// aapt resource value: 0x7f06006d
			public const int textView4 = 2131099757;
			
			// aapt resource value: 0x7f060001
			public const int whoTurn = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Chess = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Chessboard = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int square = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int callHistory = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
